_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.6
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
arch:
    value: null
backbone:
    value: null
batch_size:
    value: null
computer:
    value: Air-von-Wiebke.fritz.box
cyclic_mode:
    value: null
dataset:
    value: null
fp16:
    value: null
initial_lr:
    value: null
log_freq:
    value: null
loss_name:
    value: null
mixup_alpha:
    value: null
n_iterations:
    value: null
n_lr_cycles:
    value: null
num_workers_per_gpu:
    value: null
optim:
    value: null
seed:
    value: null
task:
    value: null
use_augmentation:
    value: null
use_grad_clipping:
    value: null
use_input_clipping:
    value: null
use_label_rescaling:
    value: null
use_memmap:
    value: null
use_mixup:
    value: null
use_pretrained_model:
    value: null
use_standardization:
    value: null
use_swa:
    value: null
use_weighted_sampler:
    value: null
use_weighting_quantile:
    value: null
weight_decay:
    value: null
