_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.6
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
arch:
    value: unet
backbone:
    value: resnet50
batch_size:
    value: 5
computer:
    value: vpn-pool1-pnt-31634.uni-muenster.de
cyclic_mode:
    value: triangular2
dataset:
    value: /mock_dataset
device:
    value: cpu
fp16:
    value: false
initial_lr:
    value: 0.001
log_freq:
    value: 5
loss_name:
    value: shift_huberf
n_iterations:
    value: 100
n_lr_cycles:
    value: 0
num_workers_per_gpu:
    value: 8
optim:
    value: AdamW
seed:
    value: 1
use_augmentation:
    value: false
use_grad_clipping:
    value: false
use_input_clipping:
    value: false
use_label_rescaling:
    value: false
use_memmap:
    value: false
use_mixup:
    value: false
use_pretrained_model:
    value: false
use_standardization:
    value: false
use_swa:
    value: false
use_weighted_sampler:
    value: g10
use_weighting_quantile:
    value: 10
weight_decay:
    value: 0.01
